<?php

namespace Versionable\Ferret\Detector;

use Versionable\Ferret\Metadata\Metadata;

/**
 * Test class for Pathinfo.
 * Generated by PHPUnit on 2010-10-09 at 20:06:58.
 *
 * @group Ferret
 */
class PathinfoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Pathinfo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

      $this->object = new Pathinfo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testDetect()
    {
      $metadata = new Metadata;
      $metadata->set(Metadata::RESOURCE_NAME_KEY, __DIR__.'/../../../data/unit.txt');

      $this->assertEquals('text/plain', $this->object->detect(null, $metadata));
    }

    public function testDetectFail()
    {
      $metadata = new Metadata;
      $metadata->set(Metadata::RESOURCE_NAME_KEY, __DIR__.'/../../../data/unit.false');

      $this->assertFalse($this->object->detect(null, $metadata));
    }

    public function testSetMapping()
    {
      $this->assertTrue($this->object->setMapping(array('txt' => 'text/plain')));
    }

    public function testSetMappingFail()
    {
      $this->assertFalse($this->object->setMapping(null));
    }
}
